# Generated by Django 4.1.1 on 2022-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("code", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=300)),
            ],
        ),
    ]
