# Generated by Django 4.1.1 on 2022-10-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_balance_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prize", models.PositiveIntegerField()),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.balance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_passives", models.PositiveIntegerField()),
                ("total_actives", models.PositiveIntegerField()),
                ("is_balanced", models.BooleanField(default=False)),
                (
                    "actives",
                    models.ManyToManyField(related_name="actives", to="api.item"),
                ),
                (
                    "passives",
                    models.ManyToManyField(related_name="passives", to="api.item"),
                ),
            ],
        ),
    ]
