# Generated by Django 4.1.1 on 2022-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_item_checkbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkbalance",
            name="actives",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="actives", to="api.item"
            ),
        ),
        migrations.AlterField(
            model_name="checkbalance",
            name="passives",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="passives", to="api.item"
            ),
        ),
        migrations.AlterField(
            model_name="checkbalance",
            name="total_actives",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="checkbalance",
            name="total_passives",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
